#include "statewright/egcf/approval.hpp"

#include "ledger_support.hpp"
#include "statewright/common/error.hpp"
#include "statewright/contracts/typed_id.hpp"

#include <algorithm>
#include <string>
#include <utility>

namespace statewright::egcf {
namespace {

[[noreturn]] void approval_error(std::string message) {
  throw common::Error(common::ErrorCode::policy_denied,
                      "EGCF approval: " + std::move(message));
}

[[nodiscard]] bool expired(std::string_view expires_at) {
  return !expires_at.empty() && expires_at <= ledger_support::utc_now();
}

} // namespace

ApprovalManager::ApprovalManager(EgcfStore &store,
                                 const core::Workspace &workspace)
    : store_(store), workspace_(workspace) {}

std::string ApprovalManager::authorize(
    std::string_view plan_id, std::string approver, std::string authority,
    contracts::Json constraints, std::string expires_at, bool human,
    int use_limit) {
  const auto stored_plan = store_.get(plan_id);
  if (stored_plan.object_type != "execution-plan") {
    approval_error("not an execution plan: " + std::string(plan_id));
  }
  if (!human) {
    approval_error(
        "human approval records cannot be generated by a model or workflow");
  }
  if (approver.empty() || authority.empty()) {
    approval_error(
        "approval requires an approver and external authority statement");
  }
  if (!constraints.is_object()) {
    approval_error("approval constraints must be an object");
  }
  const auto plan = execution_plan_from_json(stored_plan.payload);
  if (plan.source_snapshot_hash != workspace_.snapshot_hash()) {
    approval_error("execution plan source snapshot is stale");
  }
  const auto plan_parts = contracts::parse_typed_id(plan_id);
  ApprovalRecord record = {
      .plan_id = std::string(plan_id),
      .plan_hash = plan_parts.digest,
      .approver = std::move(approver),
      .authority = std::move(authority),
      .constraints = std::move(constraints),
      .created_at = ledger_support::utc_now(),
      .expires_at = std::move(expires_at),
      .use_limit = std::clamp(use_limit, 1, 20),
      .use_count = 0,
      .human = true};
  const std::string approval_id = store_.register_record(
      {.object_type = "approval", .payload = to_json(record)},
      "egcf_human_approval");
  if (approval_id != record.object_id()) {
    approval_error("approval identity mismatch");
  }
  return approval_id;
}

ApprovalRecord ApprovalManager::validate(const ExecutionPlan &plan,
                                         std::string_view approval_id) const {
  const auto stored = store_.get(approval_id);
  if (stored.object_type != "approval") {
    approval_error("not an approval record: " + std::string(approval_id));
  }
  const auto approval = approval_from_json(stored.payload);
  if (approval.plan_id != plan.object_id()) {
    approval_error("approval is bound to a different execution plan");
  }
  if (approval.plan_hash !=
      contracts::parse_typed_id(plan.object_id()).digest) {
    approval_error("approval plan hash does not match the execution plan");
  }
  if (!approval.human) {
    approval_error("human approval is required");
  }
  if (expired(approval.expires_at)) {
    approval_error("approval has expired");
  }
  if (plan.source_snapshot_hash != workspace_.snapshot_hash()) {
    approval_error("source snapshot changed after approval");
  }
  const auto &constraints = approval.constraints;
  const auto require_string_match = [&constraints](std::string_view key,
                                                    std::string_view expected) {
    const auto found = constraints.find(std::string(key));
    if (found != constraints.end() &&
        (!found->is_string() || found->get<std::string>() != expected)) {
      approval_error("approval constraint does not match " +
                     std::string(key));
    }
  };
  require_string_match("source_snapshot_hash", plan.source_snapshot_hash);
  require_string_match("graph_hash", plan.graph_hash);
  const auto digests = constraints.find("algorithm_digests");
  if (digests != constraints.end() &&
      (!digests->is_array() ||
       digests->get<std::vector<std::string>>() != plan.algorithm_digests)) {
    approval_error("approval constraint does not match algorithm_digests");
  }
  const auto allowed_nodes = constraints.find("allowed_nodes");
  if (allowed_nodes != constraints.end()) {
    if (!allowed_nodes->is_array()) {
      approval_error("approval allowed_nodes constraint must be an array");
    }
    const auto allowed = allowed_nodes->get<std::vector<std::string>>();
    if (!std::ranges::all_of(plan.node_order, [&allowed](const auto &node) {
          return std::ranges::find(allowed, node) != allowed.end();
        })) {
      approval_error("approval does not allow every execution-plan node");
    }
  }
  const auto max_actions = constraints.find("max_actions");
  if (max_actions != constraints.end() &&
      (!max_actions->is_number_integer() || max_actions->get<std::int64_t>() < 0 ||
       static_cast<std::uint64_t>(max_actions->get<std::int64_t>()) <
           plan.node_order.size())) {
    approval_error("approval max_actions constraint is insufficient");
  }
  int prior_uses = 0;
  for (const auto &execution : store_.list("execution")) {
    const auto record = execution_from_json(execution.payload);
    if (record.plan_id == plan.object_id() && record.node_id == "__workflow__" &&
        (record.status == "COMPLETED" || record.status == "SIMULATED")) {
      ++prior_uses;
    }
  }
  if (prior_uses >= approval.use_limit) {
    approval_error("approval use limit is exhausted");
  }
  return approval;
}

} // namespace statewright::egcf
